### ISSUE TITLE
Error run with tpu

### ISSUE THREAD

**Issue by vnvdev** [komo135/traderl-web-app#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/tmp/tmps5b3yc_w/github_app.py", line 305, in <module>
    app.agent_train()
  File "/tmp/tmps5b3yc_w/github_app.py", line 229, in agent_train
    self.agent.train()
  File "/tmp/tmps5b3yc_w/github_app.py", line 118, in train
    self._train(epoch, batch_size)
  File "/usr/local/lib/python3.10/dist-packages/traderl/agent/dqn.py", line 340, in _train
    target_a = self.model.predict(new_states + noise, 102800)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicatedInput' used by {{node input0}} with these attrs: [is_mirrored_variable=false, is_packed=false, index=-1, N=8, T=DT_INT32]
Registered devices: [COMPOSITE, CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[input0]] [Op:__inference_predict_function_42900]

**Comment by vnvdev** [comment]
Im using google colab tpu. But can when train with tpu do not exist
